services:
  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - 3000:3000
    env_file:
      - ./inventory/.env
    environment:
      - DATABASE_URL="mysql://root@host.docker.internal:3306/next_inventory"
      - NEXTAUTH_SECRET="NEXTAUTH_SECRET"
      - NEXTAUTH_URL="http://localhost:3000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
