services:
  inventory:
    build:
      context: ./inventory
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - 3000:3000
    env_file:
      - ./inventory/.env
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
